### ISSUE TITLE
go through SOGPF changelog and confirm new assets were added

### ISSUE THREAD

**Issue by SunStalker** [SunStalker/KP-Liberation#2]
https://community.sogpf.com/d/4-official-dlc-changelog

https://wiki.sogpf.com/index.php/Category:Assets

Better respawn vehicle, maybe m113 medical

**Comment by SunStalker** [comment]
Missing some aircraft because I am unsure about how many are needed.

**Comment by FatRefrigerator** [comment]
Thank you for bringing this up, I didn't realize truly how many small arms were missing from the arsenal preset. The list of available guns is about to double.
